In [1]:
import re
import csv
import sqlite3


lines = tuple( open("london_org.txt").read().splitlines())
#text = open("lasvegas_booking.txt", "r")

#lines = text.readlines()
conn = sqlite3.connect('london_org_1.db')
c = conn.cursor()
#c.execute("DROP TABLE hotels")
c.execute('''CREATE TABLE IF NOT EXISTS
         hotels(name text, region text, country text, address text, description text, pricerange text, rating float, 
         room1cap int, room1name text, room1bed text, room2cap int, room2name text, room2bed text, room3cap int, 
         room3name text, room3bed text, room4cap int, room4name text, room4bed text)''')

index = []
for line in lines:
    if"index " in line:
        index.append(lines.index(line))
#print(index)
loop = len(index)
for i in range(loop-1):
    count = int(0)
    for line in lines[index[i]:index[i+1]]:
        
        if line[0:4] == 'name':
            name = str(line[6:])
        if line[0:6] == 'region':
            region = str(line[8:])
        if line[0:7] == 'country':
            country = str(line[9:])
        if line[0:7] == 'address':
            address = str(line[9:])
        if line[0:11] == 'description':
            description = str(line[13:])
        if line[0:10] == 'pricerange':
            pricerange = str(line[12:])
        if line[0:6] == 'rating':
            if line[8:] != 'na':
                rating = float(line[8:])
            else:
                rating = float(0)
        if (line[0:12] == 'roomcapacity' and count<5):
 
            if count ==0:
                room1cap = int(line[14:])
                stri = str(lines[lines.index(line)+1])
                room1name = str(stri[9:])
            if count ==1:
                room2cap = int(line[14:])
                stri = str(lines[lines.index(line)+2])
                room2name = str(stri[9:])
            if count ==2:
                room3cap = int(line[14:])
                stri = str(lines[lines.index(line)+3])
                room3name = str(stri[9:])
            if count ==3:
                room4cap = int(line[14:])
                stri = str(lines[lines.index(line)+4])
                room4name = str(stri[9:])
   #         if count ==4:
        #        if  (line[14:]) == None:
       #             room5cap = int(0),room1cap,room1name,room2cap,room2name,room3cap,room3name,room4cap,room4name
       #         else:
       #             room5cap = int(line[14:]),room1cap,room1name,room2cap,room2name,room3cap,room3name,room4cap,room4name
            count = count+1
        
    
    param = [name,region,country,address,description,pricerange,rating]
    c.execute('INSERT INTO hotels(name,region,country,address,description,pricerange,rating) VALUES (?,?,?,?,?,?,?)',param)
    c.execute("commit")

In [ ]:
  
    '''
    if "name: " in line:
        string = line
        index = string.index(":")
        name = string[index+2 :]
       
        namestr = str(name)
        param = [namestr]
        c.execute('INSERT INTO hotels(name) VALUES (?)',param)
        c.execute("commit")
    if "region: " in line:
        string = line
        index = string.index(":")
        name = string[index+2 :]
       
        namestr = str(name)
        param = [namestr]
        c.execute('INSERT INTO hotels(region) VALUES (?)',param)
        c.execute("commit")
    if "country: " in line:
        string = line
        index = string.index(":")
        name = string[index+2 :]
       
        namestr = str(name)
        param = [namestr]
        c.execute('INSERT INTO hotels(country) VALUES (?)',param)
        c.execute("commit")
    if "address: " in line:
        string = line
        index = string.index(":")
        name = string[index+2 :]
       
        namestr = str(name)
        param = [namestr]
        c.execute('INSERT INTO hotels(address) VALUES (?)',param)
        c.execute("commit")
        

        '''